# Note that the example .travis.yml file for child projects lives in /install.
sudo: false
language: php

php:
  - 5.6

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.nvm"
  - "vendor"

notifications:
  # slack: acquia:KKfgpOkDhcO26Erv5uoZMfdP

addons:
  ssh_known_hosts:
  - svn-4702.devcloud.hosting.acquia.com

before_install:
  - phpenv config-rm xdebug.ini
  - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - mysql -e 'CREATE DATABASE drupal;'

install:
  - composer install --prefer-source
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/vendor/bin

before_script:
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
  # Enable $_ENV variables in PHP.
  # Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


script:
  # Generate a new 'bolted' project.
  - ./task.sh bolt:configure
  - ./task.sh bolt:create
  # Call targets in the new 'bolted' project.
  - ../bolted8/task.sh build:validate:test -Dbehat.run-server=true -Dbehat.launch-phantom=true
  # Deploy build artifact.
  - export DEPLOY_PR=true
  - ../bolted8/scripts/deploy/travis-deploy.sh 8.x 8.x-build
  # Validate and run 'bolt' phpunit tests.
  - phpcs --standard=../bolted8/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml tests
  - phpunit tests
