language: php

php:
  - 5.5

cache:
  bundler: true
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

env:
  - COMPOSER_BIN_DIR=$TRAVIS_BUILD_DIR/bin'

notifications:
  email:
    - matthew.grasmick@acquia.com
  slack: acquia:KKfgpOkDhcO26Erv5uoZMfdP

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - composer selfupdate

install:
  # The project contains two composer.json files, one for the new project
  # and one for the installer.
  - composer install --prefer-source
  - composer install --working-dir=install
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_script:
  # Create a mock mail system so Drupal install can send email somewhere.
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -r 'echo PHP_VERSION;'`/etc/php.ini"

  # Install Apache
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/travis/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # Create Database
  - mysql -e 'CREATE DATABASE travis_ci_pt;'

  # Build the codebase
  - phing -f build/phing/build.xml build

script:
  # Run tests
  - phing -f build/phing/build.xml run-tests
