# Note that the example .travis.yml file for child projects lives in /install.
sudo: false
language: php

php:
  - 5.5

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

env:
  matrix:
    - TEST_SUITE=validate:all
    - TEST_SUITE='pt:configure pt:self-test'

notifications:
  slack: acquia:KKfgpOkDhcO26Erv5uoZMfdP

before_install:
  - composer selfupdate
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - mysql -e 'CREATE DATABASE drupal;'

install:
  - composer install
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_script:
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*

script:
  - phing -f build/phing/build.xml $TEST_SUITE
