# Note that the example .travis.yml file for child projects lives in /install.
sudo: false
language: php

php:
  - 5.5

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

notifications:
  # slack: acquia:KKfgpOkDhcO26Erv5uoZMfdP

addons:
  ssh_known_hosts:
  - svn-4368.devcloud.hosting.acquia.com

before_install:
  - composer selfupdate
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - mysql -e 'CREATE DATABASE drupal;'

install:
  - composer install
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_script:
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*

script:
  - ./task.sh bolt:configure
  - ./task.sh bolt:create
  - ../bolted/task.sh setup:build:all
  - ../bolted/task.sh deploy:build:all
  - ../bolted/task.sh setup:drupal:install
  - ../bolted/task.sh setup:git-hooks
  - ../bolted/task.sh tests:security-updates
  - ../bolted/task.sh tests:behat -Dbehat:run-server=true
  - ../bolted/task.sh tests:phpunit
  - phpunit tests
