sudo: false
language: php

php:
  - 5.5

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  matrix:
    - TEST_SUITE=validate:all
    - TEST_SUITE=test:all
  global:
    secure: "nejyf8CI6gXkpetXe7Uaj+RvAMfM9FVGBz7LmZOTJHPA/yAwwhXGTCCPzM3sd18EQZegLcLo/SDRBJVOXGcERYEVkmfouYgsZIc72ds2BzLV0ukyVCf+Vjk2epkfnFpZPmjCSbrNVhFgdbjf8PGIl7v6HjQK6mBHg1PbLC6Pcvc="

notifications:
  email:
    - matthew.grasmick@acquia.com
  slack: acquia:KKfgpOkDhcO26Erv5uoZMfdP

before_install:
  - composer selfupdate

install:
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer install --prefer-source
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_script:
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
script:
  - phing -f build/phing/build.xml $TEST_SUITE
