# Note that the example .travis.yml file for child projects lives in /install.
sudo: false
language: php

php:
  - 5.5

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

notifications:
  # slack: acquia:KKfgpOkDhcO26Erv5uoZMfdP

addons:
  ssh_known_hosts:
  - svn-4702.devcloud.hosting.acquia.com

before_install:
  - composer selfupdate
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - mysql -e 'CREATE DATABASE drupal;'

install:
  - composer install
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_script:
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
  # Enable $_ENV variables in PHP.
  - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  # Generate a new 'bolted' project.
  - ./task.sh bolt:configure
  - ./task.sh bolt:create
  # Call targets in the new 'bolted' project.
  - ../bolted8/task.sh setup
  - ../bolted8/task.sh tests:all -Dbehat:run-server=true
  # Deploy in-place repo build.
  - export TEST_SUITE=bolt
  - export DEPLOY_PR=true
  - ../bolted8/scripts/deploy/travis-deploy.sh bolt 8.x 8.x-build
  # Deploy separate build artifact.
  - ../bolted8/task.sh deploy:artifact
  # Run 'bolt' phpunit tests.
  - phpunit tests
