project:
  machine_name: 'ps_project'
  human_name: 'PS Project'
  local_url: 'drupal.dev'
  # Located in /scripts/make.
  make_file: 'project.make.yml'

# staging the table of contents
docs:
  developer-guide: 'Developer Guide'
  drupal-architecture-template: 'Architecture Template'
  os-contribution: 'Open Source Contribution Guidelines'
  theming: 'Front End Handbook'

vm:
  enable: true
  dir_name: 'box'
  # This bootstraps the virtual machine.
  bootstrap: true
  # This loads the necessary ansible requirements. May interfere with other VMs
  rebuild_requirements: true

git:
  hooks:
    - commit-msg
    - pre-commit
  remotes:
    origin: 'git@github.com:[user]/[project].git'
    upstream: 'git@github.com:acquia-pso/[project].git'
    acquia: '[project-user]@[project-host].prod.hosting.acquia.com:[project-name].git'

testing_framework:
  enable: true
  javascript_driver: 'selenium2'
  # javascript_driver: 'Selenium2 / Phantom.js'

# These map to /docroot/sites/all/settings/[key].settings.php partials.
starter_settings:
  enable: true
  akamai: true
