project:
  # The acquia_subname value is the machine name of your subscription on Acquia
  # Cloud. E.g., if your dev env URL on Acquia Cloud is
  # http://psprojectdev.prod.acquia-sites.com/ then your acquia_subname is
  # "psproject". This value is used to correctly configure settings in
  # settings.php includes. This will also determine the the directory name
  # of the new repository.
  acquia_subname: 'psproject'
  human_name: 'PS Project'
  # This is used for configuring your local $base_url.
  local_url: 'http://localhost/'
  # This is the default makefile that will be used to build dependencies.
  # You do not need to change this. It is located in /scripts.
  make_file: 'project.make.yml'
  # Please ensure your profile is also in your make file.
  install_profile: 'standard'

# The following documents will be copied into the new repository. Comment-out
# any line to prevent it from being copied.
docs:
  developer-guide: 'Developer Guide'
  drupal-architecture-template: 'Architecture Template'
  os-contribution: 'Open Source Contribution Guidelines'
  theming: 'Front End Handbook'

# Configuration for the Ansible Drupal VM. To prevent inclusion of a vm, remove
# the "vm" key.
vm:
  # If true, this provisions and launches the virtual machine as part of the
  # installation process. Note that dependencies (vagrant, ansible, virtual box)
  # must be installed for this work.
  # @see /box
  bootstrap: false
  # This loads the necessary ansible requirements.
  rebuild_requirements: true
  # Sets Drush Version. Currently Acquia Cloud uses 6.6.0.
  drush_version: 6.6.0
  # Informs the VM which version of Drupal to run.
  drupal_major_version: 7
  # Comment out any extra VM utilities you don't want to install. If you don't want
  # to install *any* extras, make set this value to an empty set, e.g. `[]`.
  installed_extras:
    # GUI for database utility, [local_url]/adminer.
    #- adminer
    # Catches mail generated from local system, [local_url]:8025.
    - mailhog
    # Local memcache instance
    - memcached
    # GUI for log utility, pimpmylog.[local_url].
    - pimpmylog
    # Local SOLR instance, [local_url]:8443/solr.
    - solr
    # Local Varnish instance.
    - varnish
    # Turn on Xdebug.
    - xdebug
    # Local XHProf instance, xhprof.[local_url].
    - xhprof


# Configuration settings for new git repository.
git:
  # These git hooks will be installed in .git/hooks.
  hooks:
    # Validates commit message syntax prior to local git commits.
    - commit-msg
    # Runs PHP Code Sniffer prior to local git commits.
    - pre-commit
  # The following remotes will be configured. You must replace the bracketed
  # values below. They are not tokenized.
  # @todo Tokenize the tokens!
  remotes:
    github: 'git@github.com:[user]/[project].git'
    acquia: '[project-user]@[project-host].prod.hosting.acquia.com:[project-name].git'

# The testing framework is limited to the `tests` directory, and includes
# example tests and configuration for Behat, PHPUnit, and JMeter. To prevent
# this from being copied, remove the 'testing_framework' key.
testing_framework:
  behat:
    javascript_driver: 'selenium2'

# These map to /docroot/sites/all/settings/[key].settings.php partials.
starter_settings:
  enable: true
  akamai: true
