project:
  machine_name: 'ps_project'
  human_name: 'PS Project'
  local_url: 'drupal.dev'
  # Located in /scripts/make.
  make_file: 'project.make.yml'

vm:
  enable: true
  dir_name: 'box'

upstream_repository:
  enable: true
  name: 'upstream'
  url: 'https://github.com/acquia-pso/[project].git'

fork_repository:
  enable: true
  name: 'origin'
  url: 'https://github.com/[user]/[project].git'

testing_framework:
  enable: true
  driver: 'Zombie.js'
  # driver: 'Selenium2 / Phantom.js'

# These map to /conf/settings/[key].settings.php partials.
starter_settings:
  enable: true
  akamai: true
