<?php
/**
 * @file
 * Examples on how to implement common theming patterns.
 */

/*
 * Implements hook_ctools_plugin_directory.
 *
 * This tells ctools to look for layouts and panels (content types) inside the plugins folder.
 */
function panel_layout_example_ctools_plugin_directory($module, $plugin_type) {
  if (in_array($module, array('ctools', 'panels')) && !empty($plugin_type)) {
    return "plugins/$plugin_type";
  }
}
