<?php
/**
 * @file
 * Examples on how to implement common theming patterns.
 */


/**
 * Implements hook_theme().
 */
function custom_component_example_theme($existing, $type, $theme, $path) {
  if ($type == 'module') {
    return array(
      // This example uses a template structure. We pass the template a render array and this render array is processed by the template.
      'custom_component_example_example_pane' => array(
        'render element' => 'content',
        'template' => 'custom-component-example-example-pane',
        'path' => drupal_get_path('module', 'custom_component_example') . '/templates',
      ),
    );
  }
  return array();
}

/*
 * Implements hook_ctools_plugin_directory.
 *
 * This tells ctools to look for layouts and panels (content types) inside the plugins folder.
 */
function custom_component_example_ctools_plugin_directory($module, $plugin_type) {
  if (in_array($module, array('ctools', 'panels')) && !empty($plugin_type)) {
    return "plugins/$plugin_type";
  }
}
