<?php
/**
 * @file
 * Examples on how to implement common theming patterns.
 */

/**
 * Here we define a library. This let's up group assets into one re-usable definition. If you add a library multiple times, it is only included once on the rendered page.
 */

/**
 * Implements hook_library().
 */
function add_js_example_library() {

  $libraries['example_library'] = array(
    'title' => 'Example Library',
    'website' => 'http://www.example.com/exampleLibrary',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'add_js_example') . '/js/example_library.js' => array(
        'type' => 'file',
        'scope' => 'header',
        'group' => JS_LIBRARY,
        // This tells the system that this will be on every page and influences aggregation.
        'every_page' => TRUE,
        // This tells the system to aggregate this js.
        'preprocess' => TRUE,
      ),
    ),
    'css' => array(
      drupal_get_path('module', 'add_js_example') . '/css/example.css',
    ),
  );
}

/**
 * Here we create a block and attach javascript and libraries to it. This is the recommended approach. #attached will be stored in the cache while drupal_add_js() may not be. When loaded from the cache, or otherwise, all of the items defined in #attached are then processed as late as possible using functions like drupal_add_js().
 */

/**
 * Implements hook_block_info().
 */
function add_js_example_block_info() {
  $blocks['acquia_examples_block'] = array(
    'info' => t('Acquia Examples Block'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This will only apply to the one block.
 */
function add_js_example_block_view($delta = '') {
  $block = array();

  if ($delta === 'acquia_examples_block') {
    $block['subject'] = t('Example Block');
    $block['content'] = array(
      '#type' => 'markup',
      '#markup' => t('hello world'),
      '#attached' => array(
        'js' => array(
          // Module file.
          drupal_get_path('module', 'acquia_examples') . '/js/acquia_examples.js',
          // External file.
          'http://example.com/other_library.js' => array(
            'type' => 'external',
          ),
          // Add a setting.
          array(
            'type' => 'setting',
            'data' => array(
              'acquiaExamples' => array('Example Setting from Block'),
            ),
          ),
        ),
        'library' => array(
          array('acquia_examples', 'example_library'),
        ),
      ),
    );
  }

  return $block;
}


/**
 * Here we use a preprocess function to attach javascript and libraries. Most of the time you will want to use #attached.
 */

/**
 * Implements hook_preprocess_hook().
 *
 * This will run on every page.
 */
function add_js_example_preprocess_page(&$variables) {
  // Add a library.
  drupal_add_library('add_js_example', 'example_library');

  // Add a JS file.
  drupal_add_js(drupal_get_path('module', 'add_js_example') . '/js/example.js');

  // Add a variable that will be available as Drupal.settings.acquiaExamples.
  // Because the setting is an array, it will be combined with the block in hook_block_view() used in this module.
  drupal_add_js(array('acquiaExamples' => array('Example Setting from Page')), 'setting');
}
