#!/usr/bin/env bash
#
# To enable this hook, developers should place it in .git/hooks/.
#
# You may adapt the message length check. Currently checking it's longer than 15 characters.

regex="^${project.prefix}-[0-9]+( |: )[^ ].{15,}"
if ! grep -iqE "$regex" "$1"; then
  echo "Invalid commit message."
  echo "Valid example: ${project.prefix}-135 Add the new picture field to the article feature."
  exit 1;
fi
